# Generated by Django 3.1.3 on 2020-12-04 23:30

from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True, validators=[domains.models._simple_domain_name_validator])),
                ('name', models.CharField(max_length=128)),
            ],
            managers=[
                ('objects', domains.models.DomainManager()),
            ],
        ),
    ]
